from __future__ import annotations

import os
import random

import torch


BASE_MODEL = "stabilityai/stable-diffusion-xl-base-1.0"
LIGHTNING_REPO = "ByteDance/SDXL-Lightning"
LIGHTNING_CHECKPOINT = "sdxl_lightning_4step_unet.safetensors"


def load_sdxl_lightning(model_id=LIGHTNING_REPO):
    """
    Load SDXL Base 1.0 with the official SDXL-Lightning 4-step UNet.

    The Lightning repository is a checkpoint repository, not a complete
    Diffusers pipeline, so the Lightning UNet must be loaded into the
    SDXL Base pipeline.
    """

    from diffusers import (
        EulerDiscreteScheduler,
        StableDiffusionXLPipeline,
        UNet2DConditionModel,
    )
    from huggingface_hub import hf_hub_download
    from safetensors.torch import load_file

    device = "cuda" if torch.cuda.is_available() else "cpu"

    if device == "cuda":
        dtype = torch.float16
    else:
        dtype = torch.float32

    print("[IMAGE] Loading SDXL Base architecture...")

    # Load the SDXL UNet architecture.
    unet = UNet2DConditionModel.from_config(
        BASE_MODEL,
        subfolder="unet",
    )

    # Download the official 4-step Lightning UNet checkpoint.
    print("[IMAGE] Downloading SDXL-Lightning 4-step UNet...")

    checkpoint_path = hf_hub_download(
        repo_id=model_id,
        filename=LIGHTNING_CHECKPOINT,
    )

    print(f"[IMAGE] Lightning checkpoint: {checkpoint_path}")

    # Load Lightning weights.
    print("[IMAGE] Loading Lightning weights...")

    state_dict = load_file(
        checkpoint_path,
        device="cpu",
    )

    unet.load_state_dict(
        state_dict,
        strict=True,
    )

    del state_dict

    # Convert the UNet to the appropriate dtype.
    unet = unet.to(dtype=dtype)

    print("[IMAGE] Building SDXL-Lightning pipeline...")

    pipe = StableDiffusionXLPipeline.from_pretrained(
        BASE_MODEL,
        unet=unet,
        torch_dtype=dtype,
        variant="fp16" if device == "cuda" else None,
        use_safetensors=True,
        add_watermarker=False,
    )

    # SDXL-Lightning uses the trailing timestep schedule.
    pipe.scheduler = EulerDiscreteScheduler.from_config(
        pipe.scheduler.config,
        timestep_spacing="trailing",
    )

    if device == "cuda":
        # Keep the model usable on a Colab T4.
        pipe.enable_model_cpu_offload()

        # VAE memory optimizations.
        pipe.vae.enable_slicing()
        pipe.vae.enable_tiling()

    else:
        pipe = pipe.to(device)

    pipe.set_progress_bar_config(disable=True)

    print("[IMAGE] SDXL-Lightning 4-step ready.")

    return pipe


def _scene_prompt(scene):
    """
    Select the best prompt generated by the Qwen scene processor.

    image_prompt is preferred because it is intended specifically for
    image generation. Older scene files can still fall back to the
    other fields.
    """

    prompt = (
        scene.get("image_prompt")
        or scene.get("visual_description")
        or scene.get("image_description")
    )

    if not prompt:
        raise ValueError(
            f"Scene {scene.get('scene_id', '?')} has no image prompt."
        )

    return str(prompt).strip()


def run(
    paths,
    job_id,
    scenes,
    pipe,
    config,
    progress=None,
):
    """
    Generate missing scene images.

    Existing images are never regenerated.

    Returns:
        List of image paths in scene order.
    """

    out = paths.images_dir(job_id)
    os.makedirs(out, exist_ok=True)

    files = []
    total = len(scenes)

    width = int(config.image_width)
    height = int(config.image_height)
    steps = int(config.image_steps)
    guidance = float(config.image_guidance_scale)

    for i, scene in enumerate(scenes, 1):

        sid = int(scene["scene_id"])

        output_path = os.path.join(
            out,
            f"scene_{sid:03d}.png",
        )

        # --------------------------------------------------------
        # Resume support
        # --------------------------------------------------------

        if os.path.exists(output_path):

            print(
                f"[IMAGE] {job_id} | "
                f"scene {i}/{total} | exists, skip"
            )

            files.append(output_path)

            if progress:
                progress(i, total)

            continue

        # --------------------------------------------------------
        # Build prompt
        # --------------------------------------------------------

        prompt = _scene_prompt(scene)

        print(
            f"[IMAGE] {job_id} | "
            f"scene {i}/{total} | generating"
        )

        # --------------------------------------------------------
        # Deterministic per-scene seed
        # --------------------------------------------------------

        seed = random.randint(
            0,
            2**32 - 1,
        )

        generator = torch.Generator(
            device="cpu"
        ).manual_seed(seed)

        # --------------------------------------------------------
        # SDXL-Lightning generation
        #
        # Lightning 4-step uses:
        #   4 inference steps
        #   CFG 0
        # --------------------------------------------------------

        result = pipe(
            prompt=prompt,
            width=width,
            height=height,
            num_inference_steps=steps,
            guidance_scale=guidance,
            generator=generator,
        )

        image = result.images[0]

        image.save(
            output_path,
            format="PNG",
            optimize=True,
        )

        print(
            f"[IMAGE] {job_id} | "
            f"scene {sid:03d} | saved | "
            f"seed={seed}"
        )

        files.append(output_path)

        if progress:
            progress(i, total)

    return files
